default_language_version:
    python: python3.10
repos:
  - repo: local
    hooks:
      - id: my_pre_commit_hook
        name: Sanitize Jupyter Notebooks
        files: \.ipynb$
        entry: python3 scripts/sanitize_notebook.py
        language: python
  - repo: local
    hooks:
      - id: run_tests
        language: script
        name: Run tests
        entry: ./scripts/run_tests.sh
        stage: [commit]